---
namespace: community
name: docker_role
version: 1.0.0
readme: README.md
authors:
  - Aurelien
description: Install docker
license_file: COPYING
tags:
  - v1
repository: https://github.com/GacruxM4/docker_role.git
documentation: https://github.com/GacruxM4/docker_role.git
homepage: https://github.com/GacruxM4/docker_role.git
issues: https://github.com/GacruxM4/docker_role.git
build_ignore:
  - .gitignore