---
# tasks file for docker
- name: "Copy Script "
  template:
    src: "install_docker.sh.j2"
    dest: "/home/{{ ansible_user }}/install_docker.sh"

- name: "Execute Script"
  command: "sh /home/{{ ansible_user }}/install_docker.sh"